name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to the Github Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag name
      id: extract_tag
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Convert repo name to lowercase
      id: repo_name
      run: echo "::set-output name=repo::$(echo "${{ github.repository }}" | awk '{print tolower($0)}')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.repo_name.outputs.repo }}:${{ steps.extract_tag.outputs.version }}
